name: CD da branch main no DCX
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy da versão de produção do EducAPI Manager Front
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/ssh-remote-commands
    steps:
      - name: Conectando via ssh com chave e fazendo o deploy da aplicação
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_LOGIN }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd EducAPI-Manager-Front
            docker-compose down
            git pull origin main
            docker-compose up -d --build
